FROM lilione/fabric-peer:docker

WORKDIR /usr/src
RUN git clone https://github.com/lilione/HoneyBadgerMPC.git

# switch to fabric branch
WORKDIR /usr/src/HoneyBadgerMPC
RUN git checkout fabric

# build hbmpc
RUN pip3 install -e .['dev']

# install pairing
WORKDIR /usr/src/HoneyBadgerMPC
RUN pip3 install -v pairing/
